//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiodataCRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    //using Microsoft.EntityFrameworkCore;

    public partial class BIODATADBContext : DbContext
    {
        public object entity;
        public object builder;

        public BIODATADBContext()
            : base("name=BIODATADBContext")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //modelBuilder.Entity<BIODATA>(entity =>
            //{
            //    entity.HasKey(t => t.ID);  // Argumen pertama: tipe entitas
            //    entity.Property(t => t.ID).ValueGeneratedOnAdd();
               
            //    //entity.Property(t => t.id).ValueGeneratedOnAdd();
            //    //entity.Property(t => t.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            //});
            //throw new UnintentionalCodeFirstException();
        }

        public DbSet<BIODATA> BIODATAs { get; set; }
    }

    public class ModelBuilder
    {
        internal void Entity<T>(Action<object> p)
        {
            throw new NotImplementedException();
        }
    }
}
